course = c("DAC","DBDA","DMC","DESD")
student = c(220,100,100,150)
df1=data.frame(course,student)
print(class(df1))
print(df1)
print(class(df1$course))
print(summary(df1))

num = c(2,4,5,6,3,1,10,12)
num1 = data.frame(num)
print(num1)
print(summary(num1))

df2=read.csv('/home/sunbeam/Desktop/abc.csv')
print(df2)
print(is.data.frame(df2))
print(ncol(df2))
print(nrow(df2))
max_mark<-max(df2$mark)
print(max_mark)
retval <- subset(df2, mark == max(mark))
print(retval)
